version: '3'
services:
  hexagonal-architecture-workshop-dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: hexagonal-architecture-workshop-dynamodb-local
    ports:
      - "8000:8000"
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
